title: BCO-DMO Blog
permalink: /:year/:month/:day/:title
description: Democratizing access to ocean science data.
exclude: ["vendor", "CNAME", "Gemfile", "LICENSE", "README.md"]
google_analytics:

page_excerpts: true
excerpt_separator: <!--more-->

show_drafts: true

lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
