title: Blog | BCO-DMO - Biological and Chemical Oceanography Data Management Office
permalink: /:year/:month/:day/:title
description: Democratizing access to ocean science data.
exclude: ["vendor", "CNAME", "Gemfile", "LICENSE", "README.md"]
google_analytics:

collections:
  drafts:
    output: true
    
page_excerpts: true
excerpt_separator: "<!--more-->"

lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
